### ISSUE TITLE
Snowboy is not working

### ISSUE THREAD

**Issue by antonjudes** [shivasiddharth/DIY-Echo-Show#3]
While installing port audio was not working, so i used another link to download the port audio and installed whole.

Another issue i faced was voiceactivation.py, i am always getting below error no input device. 

JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Traceback (most recent call last):
  File "/home/pi/DIY-Echo-Show/snowboy/voiceactivation.py", line 86, in <module>
    detector = snowboydecoder.HotwordDetector(model, sensitivity=0.5)
  File "/home/pi/DIY-Echo-Show/snowboy/snowboydecoder.py", line 115, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 750, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pyaudio.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)

Please help to solve this voice activation

**Comment by antonjudes** [comment]
If i start the voiceactivation.py, it works. But if i start it after running startsampleassistant.sh, snowboy is not working. I think because the hardwares are already been used by alexa.

I have usb mic in hw 2,0 and headphone jack in hw 1,0. 
While installing the prep-system.sh, it didnt create or modify asound.conf or asoundrc. So i manually edited these files and audiotest.sh(edited usb mic hw2,0) worked. I couldnt understand to edit this audio conf file below. 

`pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:2,0"
        channels 1
    }
}

pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "hw:1,0"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}
`

I got a python audio card testing code 
`import pyaudio

pyaudio_instance = pyaudio.PyAudio()


print('\navailable devices:')

for i in range(pyaudio_instance.get_device_count()):
    dev = pyaudio_instance.get_device_info_by_index(i)
    name = dev['name'].encode('utf-8')
    print(i, name, dev['maxInputChannels'], dev['maxOutputChannels'])

print('\ndefault input & output device:')
print(pyaudio_instance.get_default_input_device_info())
print(pyaudio_instance.get_default_output_device_info())`

When i run above python script while alexavoice is running, i get below output. Which shows no audio device available, not even dsnooper
i get below output Python IDE shell: 
'available devices:
0 b'dmix' 0 2
'
Same python script gives below output when alexa is not running:
'available devices:
0 b'USB Device 0x46d:0x8c5: Audio (hw:2,0)' 1 0
1 b'dsnooper' 1 0
2 b'dmix' 0 2
3 b'default' 128 128

Usually the mic hw is always 1,0. but in my case usb mic is hw 2,0. 
Somebody please help

**Comment by antonjudes** [comment]
I had already installed a smart screen following amazon screen.
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html

i had few issues

**Comment by antonjudes** [comment]
I had installed a smart screen from this link also
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-screen-sdk/raspberry-pi.html

But now snowboy is working with that installation and not with DIY-ECHO-SHOW. So i am gonna use that with this snowboy.
