### ISSUE TITLE
error compiling screen install

### ISSUE THREAD

**Issue by shawnpaffhausen** [shivasiddharth/DIY-Echo-Show#5]
ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-05T10_32_40_108Z-debug.log
modules/GUI/CMakeFiles/GUIClient.dir/build.make:57: recipe for target 'modules/GUI/CMakeFiles/GUIClient' failed
make[2]: *** [modules/GUI/CMakeFiles/GUIClient] Error 2
CMakeFiles/Makefile2:2146: recipe for target 'modules/GUI/CMakeFiles/GUIClient.dir/all' failed
make[1]: *** [modules/GUI/CMakeFiles/GUIClient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shivasiddharth** [comment]
I am lost here. Can you please elaborate your post. Which board, which version of OS and what release, whether the voice component got installed correctly etc.

**Comment by shivasiddharth** [comment]
You have given me a snippet and it is hard to locate the source of error.

**Comment by Hans0lo** [comment]
@shawnpaffhausen
just got the EXACT same error that you got - and found this fix here:
https://github.com/alexa/alexa-smart-screen-sdk/issues/36#issuecomment-668136185

you find both files that you need to apply the fix to here:
/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components

both times the line to replace is quite at the start of the files.

-----
Thank you for bringing this to our attention!

It looks like csstype did a major version bump and broke import { VisibilityProperty } from 'csstype'; line in our code.

Went from VisibilityProperty to Property.Visibility.

You can apply this fix to the code:
type VisibilityProperty = import('csstype').Property.Visibility;
In both APLRendererWindow and VoiceChrome

We will go ahead and update this fix in our next release.

Please let us know if you are still having issue.
Thanks again!

**Comment by shawnpaffhausen** [comment]
Thanks I'll check it out after a bitSent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Hans0lo <notifications@github.com> Date: 8/14/20  14:02  (GMT-05:00) To: shivasiddharth/DIY-Echo-Show <DIY-Echo-Show@noreply.github.com> Cc: shawnpaffhausen <shawnpaffhausen@yahoo.com>, Mention <mention@noreply.github.com> Subject: Re: [shivasiddharth/DIY-Echo-Show] error compiling screen install (#5) 
@shawnpaffhausen
just got the EXACT same error that you got - and found this fix here:
alexa/alexa-smart-screen-sdk#36 (comment)


—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/shivasiddharth/DIY-Echo-Show/issues/5#issuecomment-674195497",
"url": "https://github.com/shivasiddharth/DIY-Echo-Show/issues/5#issuecomment-674195497",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by shawnpaffhausen** [comment]
ok voice installed fine..raaspberry pi3b+ stretch (raspbian 9) with updates included

this is the error you get when installing the screen component

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,10)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gui@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-21T03_20_58_036Z-debug.log
modules/GUI/CMakeFiles/GUIClient.dir/build.make:57: recipe for target 'modules/GUI/CMakeFiles/GUIClient' failed
make[2]: *** [modules/GUI/CMakeFiles/GUIClient] Error 2
CMakeFiles/Makefile2:2146: recipe for target 'modules/GUI/CMakeFiles/GUIClient.dir/all' failed
make[1]: *** [modules/GUI/CMakeFiles/GUIClient.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shawnpaffhausen** [comment]
i did the fix but still get this error

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,18)
      TS1005: ',' expected.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx
./components/APLRendererWindow.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/APLRendererWindow.tsx(23,19)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'Visibility'.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,18)
      TS1005: ',' expected.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(7,19)
      TS2305: Module '"/home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/node_modules/csstype/index"' has no exported member 'Visibility'.

ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx
./components/VoiceChrome.tsx
[tsl] ERROR in /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js/src/components/VoiceChrome.tsx(49,34)
      TS2304: Cannot find name 'VisibilityProperty'.
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
       4 modules
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI" "--define" "DISABLE_WEBSOCKET_SSL=true"`
npm ERR! Exit status 2
npm ERR!

**Comment by shawnpaffhausen** [comment]
ok applied the fix properly but get this error under the alexa-screen-installer.sh

/root/.npm/_logs/2020-08-25T22_42_02_201Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--',
1 verbose cli   '--output-path',
1 verbose cli   '/home/pi/DIY-Echo-Show/Alexa/ss-build/modules/GUI',
1 verbose cli   '--define',
1 verbose cli   'DISABLE_WEBSOCKET_SSL=true'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle gui@1.0.0~prebuild: gui@1.0.0
6 info lifecycle gui@1.0.0~build: gui@1.0.0
7 verbose lifecycle gui@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle gui@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/D$9 verbose lifecycle gui@1.0.0~build: CWD: /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js
10 silly lifecycle gui@1.0.0~build: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/DIY-Echo-Show/Alexa/$10 silly lifecycle ]
11 silly lifecycle gui@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle gui@1.0.0~build: Failed to exec build script
13 verbose stack Error: gui@1.0.0 build: `npm run lint && webpack --config webpack.config.js "--output-path" "/home/pi/$13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:$13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid gui@1.0.0
15 verbose cwd /home/pi/DIY-Echo-Show/Alexa/alexa-smart-screen-sdk/modules/GUI/js
